Update flake8 to version 3.0.8
Update flake8 to come around:
Error: There is a version conflict.
We already have: pycodestyle 2.3.1
but flake8 3.0.4 requires 'pycodestyle<2.1.0,>=2.0.0'.